CREATE TABLE user (

id   INTEGER     NOT NULL AUTO_INCREMENT,
pseudo  VARCHAR(20) NOT NULL,
pwd  VARCHAR(120) NOT NULL,
name VARCHAR(50),
lastname  VARCHAR(50),
dateOfB  DATE NOT NULL,
email VARCHAR(50) NOT NULL,
address VARCHAR(100),
PRIMARY KEY (pseudo)
);